export const POST_INGREDIENT: "POST_INGREDIENT" = "POST_INGREDIENT";
export const DELETE_INGREDIENT: "DELETE_INGREDIENT" = "DELETE_INGREDIENT";
export const NEW_ARRAY_INGREDIENT: "NEW_ARRAY_INGREDIENT" = "NEW_ARRAY_INGREDIENT";
export const MOVE_INGREDIENT: "MOVE_INGREDIENT" = "MOVE_INGREDIENT";
export const DELETE_ALL_INRGEDIENTS: "DELETE_ALL_INRGEDIENTS" = "DELETE_ALL_INRGEDIENTS";

export const GET_INGREDIENTS_FAILED: "GET_INGREDIENTS_FAILED" = "GET_INGREDIENTS_FAILED";
export const GET_INGREDIENTS_REQUEST: "GET_INGREDIENTS_REQUEST" = "GET_INGREDIENTS_REQUEST";
export const GET_INGREDIENTS_SUCCESS: "GET_INGREDIENTS_SUCCESS" = "GET_INGREDIENTS_SUCCESS";

export const GET_ORDER_FAILED: "GET_ORDER_FAILED" = "GET_ORDER_FAILED";
export const GET_ORDER_REQUEST: "GET_ORDER_REQUEST" = "GET_ORDER_REQUEST";
export const GET_ORDER_SUCCESS: "GET_ORDER_SUCCESS" = "GET_ORDER_SUCCESS";

export const REG_USER_SUCCESS: "GET_USER_SUCCESS" = "GET_USER_SUCCESS";
export const REG_USER_FAILED: "GET_USER_FAILED" = "GET_USER_FAILED";
export const REG_USER_REQUEST: "GET_USER_REQUEST" = "GET_USER_REQUEST";
export const LOG_IN_USER_REQUEST: "LOG_IN_USER_REQUEST" = "LOG_IN_USER_REQUEST";
export const LOG_IN_USER_FAILED: "LOG_IN_USER_FAILED" = "LOG_IN_USER_FAILED";
export const LOG_IN_USER_SUCCESS: "LOG_IN_USER_SUCCESS" = "LOG_IN_USER_SUCCESS";
export const LOG_OUT_USER_REQUEST: "LOG_OUT_USER_REQUEST" = "LOG_OUT_USER_REQUEST";
export const LOG_OUT_USER_FAILED: "LOG_OUT_USER_FAILED" = "LOG_OUT_USER_FAILED";
export const LOG_OUT_USER_SUCCESS: "LOG_OUT_USER_SUCCESS" = "LOG_OUT_USER_SUCCESS";
export const SET_AUTH_CHECKED: "SET_AUTH_CHECKED" = "SET_AUTH_CHECKED";
export const GET_USER_DATA_REQUEST: "GET_USER_DATA_REQUEST" = "GET_USER_DATA_REQUEST";
export const GET_USER_DATA_FAILED: "GET_USER_DATA_FAILED" = "GET_USER_DATA_FAILED";
export const GET_USER_DATA_SUCCESS: "GET_USER_DATA_SUCCESS" = "GET_USER_DATA_SUCCESS";
export const POST_USER_DATA_REQUEST: "POST_USER_DATA_REQUEST" = "POST_USER_DATA_REQUEST";
export const POST_USER_DATA_FAILED: "POST_USER_DATA_FAILED" = "POST_USER_DATA_FAILED";
export const POST_USER_DATA_SUCCESS: "POST_USER_DATA_SUCCESS" = "POST_USER_DATA_SUCCESS";

export const WS_ORDERS_FEED_CONNECTION_START: "WS_ORDERS_FEED_CONNECTION_START" = "WS_ORDERS_FEED_CONNECTION_START";
export const WS_ORDERS_FEED_CONNECTION_SUCCESS: "WS_ORDERS_FEED_CONNECTION_SUCCESS" = "WS_ORDERS_FEED_CONNECTION_SUCCESS";
export const WS_ORDERS_FEED_CONNECTION_ERROR: "WS_ORDERS_FEED_CONNECTION_ERROR" = "WS_ORDERS_FEED_CONNECTION_ERROR";
export const WS_ORDERS_FEED_CONNECTION_CLOSED: "WS_ORDERS_FEED_CONNECTION_CLOSED" = "WS_ORDERS_FEED_CONNECTION_CLOSED";
export const WS_ORDERS_FEED_GET_MESSAGE: "WS_ORDERS_FEED_GET_MESSAGE" = "WS_ORDERS_FEED_GET_MESSAGE";
export const WS_ORDERS_FEED_CONNECTION_STOP: "WS_ORDERS_FEED_CONNECTION_STOP" = "WS_ORDERS_FEED_CONNECTION_STOP";

export const WS_PROFILE_ORDERS_CONNECTION_START: "WS_PROFILE_ORDERS_CONNECTION_START" = "WS_PROFILE_ORDERS_CONNECTION_START";
export const WS_PROFILE_ORDERS_CONNECTION_SUCCESS: "WS_PROFILE_ORDERS_CONNECTION_SUCCESS" = "WS_PROFILE_ORDERS_CONNECTION_SUCCESS";
export const WS_PROFILE_ORDERS_CONNECTION_ERROR: "WS_PROFILE_ORDERS_CONNECTION_ERROR" = "WS_PROFILE_ORDERS_CONNECTION_ERROR";
export const WS_PROFILE_ORDERS_CONNECTION_CLOSED: "WS_PROFILE_ORDERS_CONNECTION_CLOSED" = "WS_PROFILE_ORDERS_CONNECTION_CLOSED";
export const WS_PROFILE_ORDERS_GET_MESSAGE: "WS_PROFILE_ORDERS_GET_MESSAGE" = "WS_PROFILE_ORDERS_GET_MESSAGE";
export const WS_PROFILE_ORDERS_CONNECTION_STOP: "WS_PROFILE_ORDERS_CONNECTION_STOP" = "WS_PROFILE_ORDERS_CONNECTION_STOP";
